apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-service-config
  labels:
    app: notifications-service
data:
  aws-region: "us-east-1"
  smtp-host: "smtp.example.com"
  smtp-port: "587"
